[theme]
primaryColor = "#800000"          # Maroon
backgroundColor = "#FFFFFF"       # White
secondaryBackgroundColor = "#FF8C00"  # Orange
textColor = "#000000"             # Black text
font = "sans serif"
